# for local development
version: '3.8'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: simple-task-list-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  db_test:
    image: postgres:13.3
    environment:
      POSTGRES_DB: simple-task-list-db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '${DB_PORT_TEST}:5432'

volumes:
  app-volume:
