# for local development
version: '3.8'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: simple-task-list-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
